version: "3.9"
services:
  app:
    image: mydesk-app
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - node_modules:/app/node_modules
    ports:
      - "4500:4200" # Map container port 80 to host port 4300
    environment:
      API_URL: http://api:8080 # Point to the Rust API
    networks:
      - mydesk_network

networks:
  mydesk_network:
    driver: bridge

volumes:
  node_modules: