version: "3.9"
services:
  app:
    image: mydesk-app
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - "4500:4200"
    networks:
      - mydesk_network

networks:
  mydesk_network:
    driver: bridge