version: "3.9"
services:
  app:
    image: mydesk-app
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: mydesk-app
    networks:
      - mydesk_network

networks:
  mydesk_network:
    external: true